### PR TITLE
Okay. Didn't get these in the last update...so....

### PR DESCRIPTION
**Pull request by Puckaboo2**
Small racial fixes, fixed Unathi and Tajara tail alignment bugs
Fixed syringe reagent color bugs, reverted it to Aztec's fix
Fixed the slime person icon mistake, but I can do nothing about the overlaying of the legs causing a loss of translucency.
Fixed the blue backwards-surgical cap icon mistake,
Made HUDs look less messy on all races
Final. Fuckin'. Medical HUD. Fix. I swear. It should work, now.
Re-sprited left and right directions of the strait jacket (it looks beautimous, now), renamed 'straight jacket' to Strait Jacket. 
Modified Mew's blood boxes; they have appropriate icons, now.
Added ability to check yourself for broken bones--message will be 'Your [body part] feels very painful to move' at the cost of overriding messages concerning burns and brute damage on that limb.
MAJOR reagent description rehaul--including drinks, condiments, chemicals, medicines, and hydroponic stuff. Scientific explanations of each reagent can be found after clicking 'analyze' in the chemmaster, next to the detected reagent.
Removed lots of meta from reagent descriptions, and added descriptions to those who did not have any.
Added colors to hydroponic bottle reagents.
Added my own drink.
Removed Deadrum because it was a redundant reagent and affected a few recipes that needed Rum.
Modified existing Tajara and Unathi suits to match the new tail models. (There are more; I need assistance in finding them. Opaq, help)
Oxygen deprivation begins at 80%, now.
Fixed 'tequila' misspell in all documents and icons. 
Made Spider meat xenomeat instead of bearmeat
Fixed some shoes
Added additional levels of hunger satiety, one for nearly no nutrition and a 'well-fed' one.
Switched dylovene and inaprovaline bottle colors
Added certain masks for Unathi and Tajara that didn't work in the last update
Tajara no longer have that 1.2 (approx +20%, I think) brute mod, so they should do the same damage as punching, except they can cause bleeds.

Just added, today:
Added Central Command and ERT PDAs! Also added a new PDA for bad guys, like assassins. Mew, you can map the PDAs if you want.
Hostile and friendly slimes no longer have faces.
Added shoe icons for Unathi and Tajaran.
IAA PDAs look more CentCom-like, dark blue with gold buttons and an NT-blue stripe.
Final final HUD fix. Seriously, u guiz, I fixed it, this time.

### CODE REVIEW

**Comment by woothie** [comment]
*stares in horror at the foot-long list*

**Comment by Puckaboo2** [comment]
Well, this is why I kept pushing for merges a while back, but no one came to look at them, so I just pulled them away...

**Comment by Davnik** [comment]
I hope you tested your shit before you did commit. Because uh, some of this could be really buggy.

Things to watch for out of this:
~Deadrum removal may have unintended consequences
~Broken bones check... at the cost of other messages? We should look into having both, yes?
~The "thirsty and want a drink" message may be a dead giveaway for blood loss, especially because we don't actually have a thirst system, so people will look into why that message exists. But that's their meta problem.
~The 1.2 brute mod on Tajarans may or may not fix the issue, or cause problems of its own; test test test.
~Much potential for hard-to-track catastrophic issues, when 42 separate commits all hit at once. As long as it's all been extensively tested, it probably shouldn't be an issue. Probably.

**Comment by aztectornado** [comment]
We'll cross that bridge when we get there. If you're really curious, merge it and we'll test things offline prior to release to server, but it compiles, and all of these sound like changes that are pretty small so far as scope goes.

I mean, worst that happens is a few drinks stop mixing. That's easy shit to fix.

**Comment by aztectornado** [comment]
I just looked through the code half of the merge. It all looks solid to me. As for the icon half, I already know Puck is pretty badass at them, so all in all, I say go for it.

**Comment by Puckaboo2** [comment]
1. Tested deadrum removal. It's alright.
2. You can't bring your limb up to look at it if it's broken. If you try, it's painful. Try moving something that's half-shredded and scorched. It's not gonna work. This is no different than when you examine yourself and the system completely ignores minor brute damage if there are major burns,
3. I'll fix it.
4. Tajara will do the same damage as everyone else; the only difference is the bleeds they cause.

**Comment by woothie** [comment]
"I mean, worst that happens is a few drinks stop mixing. That's easy shit to fix."
Worst that happens is that something in here causes some obscure fatal error which causes the server to crash, when someone tries to make cola and rum. Or some sorta near-infinite loop or CPU-guzzling domino effect bullshit, I don't know.

This needs EXTENSIVE testing from one or more others, given the ludicrous amount of tiny things changed. I don't want any of this causing the server to get a cardiac arrest because something something medHUD or whatever. I'd do it myself but uh, I'm on my way to the base, without my laptop. Too bad BYOND doesn't have an Android app, eh.

But yes, someone pull these changes to their desk and test it, purdy please c:

**Comment by aztectornado** [comment]
Woothie, did you not just read she tested it?

**Comment by woothie** [comment]
'course I did, don't get sassy with me ;o
Since we don't have a multi-stage work flow (dev/experimental branch ->
test in live environment -> push to master), we need more than one dev to
test extensive changes like this prior to going live.
Starting today anyways.
Ahem.

Tbh I always wanted to make us a proper formalized workflow, even if it was
just make -> test -> PR -> fix/discuss -> merge -> live. And now with
conscription, I'm pretty much tied to administrative work. Which is a good
opportunity to do this I guess?

Also, Puck's past work turned out broken in some instances, I'll be honest
and say this has indeed affected this. In a  good way, worked as a reminder
to actually check the stuff everyone pushes and formalize things slightly
at least.

**Comment by Puckaboo2** [comment]
I still have a few more things to test. Az and I are trying to figure out what's causing the left-arm-won't-amputate-for-shit bug and the why-are-some-of-my-body-parts-dense issue with Slimes.

Also, this new lovely 'check for injuries' system I have brewing up.

**Comment by Puckaboo2** [comment]
Uuuuugh, checks keep failing....

**Comment by woothie** [comment]
;) Give me a ping when everything ticks

**Comment by Puckaboo2** [comment]
I believe I'm ready, now!

**Comment by Puckaboo2** [comment]
Pleeease...

**Comment by aztectornado** [comment]
....Derp. Something fucked up in the strait jacket equip fix I handed her. Second while I fast track another.

**Comment by woothie** [comment]
Is everything sorted?

**Comment by aztectornado** [comment]
Yes, that's what that last commit was. inventory.dm got a little screwy, so I had to debug it, but it's okay now and works as intended.

**Pull request merged**
