### PR TITLE
Fixed a disposals problem I caused, and redid tiles in hydroponics.

### PR DESCRIPTION
**Pull request by killer99603**
Signed-off-by: killer99603 <kovackm96@gmail.com>

### CODE REVIEW

**Comment by killer99603** [comment]
I recommend updating the server as soon as possible so disposals doesn't empty into the chapel. Sorry about that. Will not happen again.

**Comment by woothie** [comment]
But chapel is the best dumping place!

**Comment by Davnik** [comment]
TRAVIS NOOOOO

**Comment by Davnik** [comment]
This was fix, right? Close if fix.

**Pull request merged**
