### PR TITLE
Banning adds notes to players

### PR DESCRIPTION
**Pull request by aztectornado**
!!THIS HAS NOT BEEN TESTED!!

It builds right, and should work right, but I have no guarantee this won't throw runtime errors since I lack a SQL database to test it on. 

I wouldn't push this out to the main server prior to testing since in the worst case, we could break our ability to place bans.

But anyway, if it works, it'll add a note to the person being banned just like jobbans do. Same code/proc call, but different message.

### CODE REVIEW

**Comment by woothie** [comment]
Don't even bother making a PR if you haven't tested the stuff. Google how
to set up a XAMPP package and test it.

Future PRs that are shown as untested will be closed without notice,
including stuff going to the to-be-made Dev branch. I want as few faulty
commits cluttering the github as possible for various reasons <3

**Comment by woothie** [comment]
Just test it and make sure it actually makes makes a change to what we currently have. I belive there is an issues entry somewhere here that specifies when it works and when it doesn't. I'll reopen the PR once someone has the time to test this.

**Comment by woothie** [comment]
Found it: #62

**Comment by aztectornado** [comment]
That's what I did. I added the add_notes proc from jobban to ban, and made it such that it details the ban. 

I'll try and test it, I guess. I was kinda hoping you'd be able to, and just hit the git with a rebase if it didn't work. Ah well, I get to learn SQL hosting.

**Pull request closed without merging**
