### PR TITLE
Loads of things

### PR DESCRIPTION
**Pull request by CitationNeeded**
Missing pipes have been added.
Moved some tanks away from a stupid place.
Field generators now start correctly set up.
Made the Singularity Cameras EMP resistant.
Gave the IA an employment records console.
Fluff things

### CODE REVIEW

**Comment by CitationNeeded** [comment]
Updating PR.

**Comment by Davnik** [comment]
wooooothie?

**Comment by killer99603** [comment]
I mean, Cite can automatically merge it if there are no issues with the Travis build thing. It doesn't have to be Woothie.

**Comment by woothie** [comment]
Files he's changed has changed in later pulls. :')

**Comment by CitationNeeded** [comment]
Forgot to close

**Pull request closed without merging**
