### PR TITLE
Scrublord and fossils

### PR DESCRIPTION
**Pull request by aztectornado**
Add scrubs to loadout selection, and add a flat 50% chance for a fossil find in xenoarch so we can actually DO something with xenofauna and xenobotany's ancient things. (Playtesting showed that you need upwards of 20 fossils to actually get a single thing. 20! That's like 18 more than you get after 3 hours of work!)

### CODE REVIEW

**Comment by aztectornado** [comment]
Oh, whoops, it DID add the vampire mode conversion I was trying to add. I thought about that when I pushed. 

Oh well, that shit's untested, but it compiles. Probably as broken as meme still though. .-.

**Comment by aztectornado** [comment]
Yeah, it is almost completely useless at this point. It's there, but there's no biting, and it definitely doesn't show up in character preferences, or secret's rotation. 

An admin COULD vampirize someone, but all they'd get is the glare ability. .-.

**Comment by woothie** [comment]
Ples do playtest your changes. I'd be picky and not merge, but we can't afford to turn down good work right now. Keep it up you glorious bastard.

**Comment by aztectornado** [comment]
I did test the vampire stuff, and it's there and 'works' so far as not breaking anything, but without a bite, vampires are essentially just people with a flash in their eyes. .-.

**Comment by woothie** [comment]
Fantastic. The penicle of SS13 code.

**Pull request merged**
